---
version: '3'
services:
    pub:
        image: xdb6:latest
        build:
          context: ../6.2
          args:
            YUMUSERNAME: ${YUMUSERNAME}
            YUMPASSWORD: ${YUMPASSWORD}
        container_name: pub
        hostname: pub
        privileged: true
        tty: true
        ports:
          - "5432"
        volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup"
          - "./:/docker"
        networks:
            public:
                ipv4_address: 10.111.220.11
        depends_on:
          - sub
        entrypoint:
          - "/docker/pub_entrypoint.sh"

    sub:
        image: centos6/epas10:latest
        build:
          context: ../../epas/10
          args:
            YUMUSERNAME: ${YUMUSERNAME}
            YUMPASSWORD: ${YUMPASSWORD}
        container_name: sub
        hostname: sub
        privileged: true
        tty: true
        ports:
          - "5432"
        volumes:
          - "/sys/fs/cgroup:/sys/fs/cgroup"
          - "./:/docker"
        networks:
            public:
                ipv4_address: 10.111.220.12

networks:
    public:
        driver: "bridge"
        ipam:
            config:
                - subnet: 10.111.220.1/24
